<p style="font-family: Arial; font-size:3.75em;color:purple; font-style:bold"><br>
Introduction to numpy:
</p><br>
<p style="font-family: Arial; font-size:1.25em;color:#2462C0; font-style:bold"><br>
Package for scientific computing with Python
</p><br>

Numerical Python, or "Numpy" for short, is a foundational package on which many of the most common data science packages are built.  Numpy provides us with high performance multi-dimensional arrays which we can use as vectors or matrices.  

The key features of numpy are:

- ndarrays: n-dimensional arrays of the same data type which are fast and space-efficient.  There are a number of built-in methods for ndarrays which allow for rapid processing of data without using loops (e.g., compute the mean).
- Broadcasting: a useful tool which defines implicit behavior between multi-dimensional arrays of different sizes.
- Vectorization: enables numeric operations on ndarrays.
- Input/Output: simplifies reading and writing of data from/to file.

<b>Additional Recommended Resources:</b><br>
<a href="https://docs.scipy.org/doc/numpy/reference/">Numpy Documentation</a><br>
<i>Python for Data Analysis</i> by Wes McKinney<br>
<i>Python Data science Handbook</i> by Jake VanderPlas



### Getting started with ndarray

**ndarrays** are time and space-efficient multidimensional arrays at the core of numpy. 

**Why do we need ndarray?** The answer can be shown with one simple example. <br>
Let's try a matrix multiplication with a scalar.

$ A = 5 \cdot \left[
    \begin{array}{c} 
      1\\
      1\\
      1\\
      1
    \end{array}
  \right] =
  \left[
    \begin{array}{c}
      5\\
      5\\
      5\\
      5
    \end{array}
  \right]
$

In [16]:
vec = [1,1,1,1]
print(5*vec) # This will repeat vec 5 times.

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


Then alternativly, we need to use a list comprehension.

In [17]:
newVec = list(5*val for val in vec)
print(newVec)

[5, 5, 5, 5]


With a ndarray, it is easy to do. 

In [2]:
import numpy as np

A = np.ones((1,4))[0]
print(A)
print(A*5)

[1. 1. 1. 1.]
[5. 5. 5. 5.]


Then, how about matrix multiplication? like

$ B = 
  \begin{bmatrix} 1 & 2 \\ 1 & 2 \end{bmatrix}
  \begin{bmatrix} 3 \\ 4 \end{bmatrix} $
  
or even matrices with higer dimensions??

In [18]:
import numpy as np

C = np.array([[1,2], [1,2]])
D = np.array([[3],[4]])
print(C)
print(D)
print()

print(C.dot(D))

[[1 2]
 [1 2]]
[[3]
 [4]]

[[11]
 [11]]


The below shows $C \odot D$ i.e., Hadamard product(aka entrywise or pointwise product).

$ C = 
  \begin{bmatrix} 3 & 3 \\ 3 & 3 \end{bmatrix}, 
  D = 
  \begin{bmatrix} 2 & 2\\ 2 & 2 \end{bmatrix} $
  
$ C \odot D = 
  \begin{bmatrix} 6 & 6 \\ 6 & 6 \end{bmatrix} $
  

In [1]:
import numpy as np

C = np.array([[3,3], [3,3]])
D = np.array([[2,2],[2,2]])
print(C)
print(D)
print()

print(C*D)

[[3 3]
 [3 3]]
[[2 2]
 [2 2]]

[[6 6]
 [6 6]]


#### How to create Rank 1 numpy arrays:

<font color=blue> NOTE </font> : *The number of dimensions* is the rank of the array, we are not talking about the "rank" of a matrix.<br>

cf.: The rank of a matrix is defined as the maximum number of linearly independent column (or row) vectors in the matrix

In [1]:
import numpy as np # This is required to use the numpy package.

an_array = np.array([3, 33, 333])  # Create a rank 1 array

print(type(an_array))              # The type of an ndarray is: "<class 'numpy.ndarray'>"

<class 'numpy.ndarray'>


In [2]:
# test the shape of the array we just created, it should have just one dimension (Rank 1)
print(an_array.shape)

(3,)


In [4]:
# To check the dimension (or rank) of the ndarray
print(an_array.ndim)

1


In [21]:
# because this is a 1-rank array, we need only one index to accesss each element
print(an_array[0], an_array[1], an_array[2]) 

3 33 333


In [22]:
an_array[0] = 888            # ndarrays are mutable, here we change an element of the array

print(an_array)

[888  33 333]


#### How to create a Rank 2 numpy array:

A rank 2 **ndarray** is one with two dimensions.  Notice the format below of [ [row] , [row] ].  2 dimensional arrays are great for representing matrices which are often useful in data science.

In [6]:
another = np.array([[11,12,13],[21,22,23]])   # Create a rank 2 array

print(another)  # print the array

print("The rank: ", another.ndim)

print("The shape is 2 rows, 3 columns: ", another.shape)  # rows x columns                   

print("Accessing elements [0,0], [0,1], and [1,0] of the ndarray: ", 
        another[0, 0], ", ",another[0, 1],", ", another[1, 0])

[[11 12 13]
 [21 22 23]]
The rank:  2
The shape is 2 rows, 3 columns:  (2, 3)
Accessing elements [0,0], [0,1], and [1,0] of the ndarray:  11 ,  12 ,  21


#### There are many way to create numpy arrays:
Here we create a number of different size arrays with different shapes and different pre-filled values.  numpy has a number of built in methods which help us quickly and easily create multidimensional arrays.

In [2]:
import numpy as np

# create a 2x2 array of zeros
ex1 = np.zeros((2,2))
print(ex1)                              

[[0. 0.]
 [0. 0.]]


In [8]:
# create a 2x2 array filled with 9.0
ex2 = np.full((2,2), 9.0)  
print(ex2)   

[[9. 9.]
 [9. 9.]]


In [4]:
import numpy as np
# create a 2x2 matrix with the diagonal 1s and the others 0
ex3 = np.eye(2,2)
print(ex3)  

[[1. 0.]
 [0. 1.]]


In [10]:
# create an array of ones
ex4 = np.ones((1,2))
print(ex4)    
print(ex4.shape)

[[1. 1.]]
(1, 2)


In [13]:
# notice that the above ndarray (ex4) is actually rank 2, it is a 2x1 array
print(ex4.shape)
print(ex4.ndim)

# which means we need to use two indexes to access an element
print()
print(ex4[0,1])

(1, 2)
2

1.0


In [29]:
# create an array of random floats between 0 and 1
ex5 = np.random.random((2,2))
print(ex5)    

[[0.99672346 0.81007733]
 [0.5523732  0.06571173]]


### Array Indexing

#### Slice indexing:

Similar to the use of slice indexing with lists and strings, we can use slice indexing to pull out sub-regions of ndarrays.

In [30]:
import numpy as np

# Rank 2 array of shape (3, 4)
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


Use array slicing to get a subarray consisting of the first 2 rows x 2 columns.

In [31]:
a_slice = an_array[:2, 1:3]
print(a_slice)

[[12 13]
 [22 23]]


When you modify a slice, you actually modify the underlying array.

In [32]:
print("Before:", an_array[0, 1])   #inspect the element at 0, 1  
a_slice[0, 0] = 1000    # a_slice[0, 0] is the same piece of data as an_array[0, 1]
print("After:", an_array[0, 1])    

Before: 12
After: 1000


#### Use both integer indexing & slice indexing

We can use combinations of integer indexing and slice indexing to create different shaped matrices.

In [14]:
# Create a Rank 2 array of shape (3, 4)
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [15]:
# Using both integer indexing & slicing generates an array of lower rank
row_rank1 = an_array[1, :]    # Rank 1 view 

print(row_rank1, row_rank1.shape, row_rank1.ndim)  # notice only a single []

[21 22 23 24] (4,) 1


In [16]:
# Slicing alone: generates an array of the same rank as the an_array
row_rank2 = an_array[1:2, :]  # Rank 2 view 

print(row_rank2, row_rank2.shape, row_rank2.ndim)   # Notice the [[ ]]

[[21 22 23 24]] (1, 4) 2


In [36]:
#We can do the same thing for columns of an array:

print()
col_rank1 = an_array[:, 1]
col_rank2 = an_array[:, 1:2]

print(col_rank1, col_rank1.shape)  # Rank 1
print()
print(col_rank2, col_rank2.shape)  # Rank 2


[12 22 32] (3,)

[[12]
 [22]
 [32]] (3, 1)


#### Array Indexing for changing elements:

Sometimes it's useful to use an array of indexes to access or change elements.

In [17]:
# Create a new array
an_array = np.array([[11,12,13], [21,22,23], [31,32,33], [41,42,43]])

print('Original Array:')
print(an_array)

Original Array:
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [38]:
# Create an array of indices
col_indices = np.array([0, 1, 2, 0])
print('\nCol indices picked : ', col_indices)

row_indices = np.arange(4)
print('\nRows indices picked : ', row_indices)


Col indices picked :  [0 1 2 0]

Rows indices picked :  [0 1 2 3]


In [39]:
# Examine the pairings of row_indices and col_indices.  These are the elements we'll change next.
for row,col in zip(row_indices,col_indices):
    print(row, ", ",col)

0 ,  0
1 ,  1
2 ,  2
3 ,  0


In [40]:
# Select one element from each row
print('Values in the array at those indices: ',an_array[row_indices, col_indices])

Values in the array at those indices:  [11 22 33 41]


In [41]:
# Change one element from each row using the indices selected
an_array[row_indices, col_indices] += 100000

print('\nChanged Array:')
print(an_array)


Changed Array:
[[100011     12     13]
 [    21 100022     23]
 [    31     32 100033]
 [100041     42     43]]


### Boolean Indexing

#### Array Indexing for changing elements:


In [4]:
# create a 3x2 array
an_array = np.array([[11,12], [21, 22], [31, 32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [43]:
# create a filter which will be boolean values for whether each element meets this condition
filter = (an_array > 15)
filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

Notice that the filter is a same size ndarray as an_array which is filled with True for each element whose corresponding element in an_array which is greater than 15 and False for those elements whose value is less than 15.

In [44]:
# we can now select just those elements which meet that criteria
print(an_array[filter])

[21 22 31 32]


In [5]:
# For short, we could have just used the approach below 
# without the need for the separate filter array.

an_array[(an_array % 2 == 0)]

array([12, 22, 32])

What is particularly useful is that we can actually change elements in the array applying a similar logical filter.  Let's add 100 to all the even values.

In [6]:
an_array[an_array % 2 == 0] +=100
print(an_array)

[[ 11 112]
 [ 21 122]
 [ 31 132]]


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

### Datatypes and Array Operations
<br><br></p>

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

#### Datatypes:
</p>

In [47]:
ex1 = np.array([11, 12]) # Python assigns the  data type
print(ex1.dtype)

int32


In [48]:
ex2 = np.array([11.0, 12.0]) # Python assigns the  data type
print(ex2.dtype)

float64


In [49]:
ex3 = np.array([11, 21], dtype=np.int64) #You can also tell Python the data type
print(ex3.dtype)

int64


In [50]:
# you can use this to force floats into integers (using floor function)
ex4 = np.array([11.1,12.7], dtype=np.int64)
print(ex4.dtype)
print()
print(ex4)

int64

[11 12]


In [51]:
# you can use this to force integers into floats if you anticipate
# the values may change to floats later
ex5 = np.array([11, 21], dtype=np.float64)
print(ex5.dtype)
print()
print(ex5)

float64

[11. 21.]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

#### Arithmetic Array Operations:

</p>

In [20]:
x = np.array([[111,112],[121,122]], dtype=np.int)
y = np.array([[211.1,212.1],[221.1,222.1]], dtype=np.float64)

print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[211.1 212.1]
 [221.1 222.1]]


In [21]:
# add
print(x + y)         # The plus sign works
print()
print(np.add(x, y))  # so does the numpy function "add"

[[322.1 324.1]
 [342.1 344.1]]

[[322.1 324.1]
 [342.1 344.1]]


In [22]:
# subtract
print(x - y)
print()
print(np.subtract(x, y))

[[-100.1 -100.1]
 [-100.1 -100.1]]

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [23]:
# multiply (Hadamard or pointwise product)
print(x * y)
print()
print(np.multiply(x, y))
print()
print(111*211.1) # x[0,0] * y[0,0]

[[23432.1 23755.2]
 [26753.1 27096.2]]

[[23432.1 23755.2]
 [26753.1 27096.2]]

23432.1


In [133]:
# divide
print(x / y)
print()
print(np.divide(x, y))
print()
print(111/211.1) # x[0,0] / y[0,0]

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]

0.5258171482709616


In [57]:
# square root
print(np.sqrt(x))

[[10.53565375 10.58300524]
 [11.         11.04536102]]


In [58]:
# exponent (e ** x)
print(np.exp(x))

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

### Statistical Methods, Sorting, and Set Operations:
<br><br>
</p>

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

#### Basic Statistical Operations:
</p>

In [3]:
# setup a random 2 x 5 matrix
arr = 10 * np.random.randn(2,5)
print(arr)

[[  8.50284192   4.36680059 -17.19186102  16.61286152  -6.58067253]
 [  0.4904324  -18.68305666  -9.22833006   6.29512966  -8.28415264]]


In [4]:
# compute the mean for all elements
print(arr.mean())

-2.3700006822037833


In [5]:
# compute the means by row
print(arr.mean(axis = 1))

[ 1.1419941  -5.88199546]


In [6]:
# compute the means by column
print(arr.mean(axis = 0))

[  4.49663716  -7.15812803 -13.21009554  11.45399559  -7.43241258]


In [7]:
# sum all the elements
print(arr.sum())

-23.700006822037835


In [8]:
# compute the medians
print(np.median(arr, axis = 1))

[ 4.36680059 -8.28415264]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

#### Sorting:
</p>


In [65]:
# create a 10 element array of randoms
unsorted = np.random.randn(10)

print(unsorted)

[-0.96823435 -1.27128487  0.74502708 -2.337494    0.373622   -1.31224884
  2.61034872  0.29263584 -0.27464919 -0.1672601 ]


In [66]:
# create copy and sort
sorted = np.array(unsorted)
sorted.sort()

print(sorted)
print()
print(unsorted)

[-2.337494   -1.31224884 -1.27128487 -0.96823435 -0.27464919 -0.1672601
  0.29263584  0.373622    0.74502708  2.61034872]

[-0.96823435 -1.27128487  0.74502708 -2.337494    0.373622   -1.31224884
  2.61034872  0.29263584 -0.27464919 -0.1672601 ]


In [67]:
# inplace sorting
unsorted.sort() 

print(unsorted)

[-2.337494   -1.31224884 -1.27128487 -0.96823435 -0.27464919 -0.1672601
  0.29263584  0.373622    0.74502708  2.61034872]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

#### Finding Unique elements:
</p>

In [68]:
array = np.array([1,2,1,4,2,1,4,2])

print(np.unique(array))

[1 2 4]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

#### Set Operations with np.array data type:
</p>

In [69]:
s1 = np.array(['desk','chair','bulb'])
s2 = np.array(['lamp','bulb','chair'])
print(s1, s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [70]:
print( np.intersect1d(s1, s2) ) 

['bulb' 'chair']


In [71]:
print( np.union1d(s1, s2) )

['bulb' 'chair' 'desk' 'lamp']


In [72]:
print( np.setdiff1d(s1, s2) )# elements in s1 that are not in s2

['desk']


In [73]:
print( np.in1d(s1, s2) )#which element of s1 is also in s2

[False  True  True]


### Broadcasting:


Introduction to broadcasting. <br>
For more details, please see: <br>
https://docs.scipy.org/doc/numpy-1.10.1/user/basics.broadcasting.html

In [26]:
import numpy as np

start = np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [27]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2])
print(add_rows)

[1 0 2]


In [31]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(start)
print()
print(add_rows)
print()
print(y)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[1 0 2]

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [33]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T

print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [34]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(start)
print()
print(add_cols)
print()
print(y)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[0]
 [1]
 [2]
 [3]]

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [79]:
# this will just broadcast in both dimensions
add_scalar = np.array([1])  
print(start+add_scalar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### Example

In [39]:
# create our 3x4 matrix
arrA = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arrA)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [37]:
# create our 1x4 array
arrB = [0,1,0,2]
print(arrB)

[0, 1, 0, 2]


In [40]:
# add the two together using broadcasting
print(arrA + arrB)

[[ 1  3  3  6]
 [ 5  7  7 10]
 [ 9 11 11 14]]


### Speedtest: ndarrays vs lists


First setup paramaters for the speed test. We'll be testing time to sum elements in an ndarray versus a list.

In [83]:
from numpy import arange
from timeit import Timer

size    = 1000000
timeits = 1000

In [84]:
# create the ndarray with values 0,1,2...,size-1
nd_array = arange(size)
print( type(nd_array) )

<class 'numpy.ndarray'>


In [85]:
# timer expects the operation as a parameter, 
# here we pass nd_array.sum()
timer_numpy = Timer("nd_array.sum()", "from __main__ import nd_array")

print("Time taken by numpy ndarray: %f seconds" % 
      (timer_numpy.timeit(timeits)/timeits))

Time taken by numpy ndarray: 0.000729 seconds


In [86]:
# create the list with values 0,1,2...,size-1
a_list = list(range(size))
print (type(a_list) )

<class 'list'>


In [87]:
# timer expects the operation as a parameter, here we pass sum(a_list)
timer_list = Timer("sum(a_list)", "from __main__ import a_list")

print("Time taken by list:  %f seconds" % 
      (timer_list.timeit(timeits)/timeits))

Time taken by list:  0.037520 seconds


### Read or Write to Disk:

#### Binary Format:

In [88]:
x = np.array([ 23.23, 24.24] )

In [89]:
np.save('an_array', x)

In [90]:
np.load('an_array.npy')

array([23.23, 24.24])

#### Text Format:

In [91]:
np.savetxt('array.txt', X=x, delimiter=',')

In [92]:
np.loadtxt('array.txt', delimiter=',')

array([23.23, 24.24])

### Additional Common ndarray Operations


#### Dot Product on Matrices and Inner Product on Vectors:


In [43]:
# determine the dot product of two matrices
x2d = np.array([[1,1],[1,1]])
y2d = np.array([[2,2],[2,2]])

print(x2d.dot(y2d))
print()
print(np.dot(x2d, y2d))

[[4 4]
 [4 4]]

[[4 4]
 [4 4]]


In [42]:
# determine the inner product of two vectors
a1d = np.array([9 , 9 ])
b1d = np.array([10, 10])

print(a1d.dot(b1d))
print()
print(np.dot(a1d, b1d))

180

180


In [44]:
# dot produce on an array and vector
print(x2d)
print()
print(a1d)
print()
print(x2d.dot(a1d))
print()
print(np.dot(x2d, a1d))

[[1 1]
 [1 1]]

[9 9]

[18 18]

[18 18]


#### Sum:


In [96]:
# sum elements in the array
ex1 = np.array([[11,12],[21,22]])

print(np.sum(ex1))          # add all members

66


In [97]:
print(np.sum(ex1, axis=0))  # columnwise sum

[32 34]


In [98]:
print(np.sum(ex1, axis=1))  # rowwise sum

[23 43]


#### Element-wise Functions: 

For example, let's compare two arrays values to get the maximum of each.

In [99]:
# random array
x = np.random.randn(8)
x

array([-1.18380859,  0.76874627,  1.24862159, -0.22351155, -0.34379685,
       -0.62731696,  2.08501427,  0.98094942])

In [100]:
# another random array
y = np.random.randn(8)
y

array([ 0.39275486, -0.90070112,  0.3354793 , -0.95451418, -1.2000958 ,
       -0.33427808,  1.29818567, -0.80085527])

In [101]:
# returns element wise maximum between two arrays

np.maximum(x, y)

array([ 0.39275486,  0.76874627,  1.24862159, -0.22351155, -0.34379685,
       -0.33427808,  2.08501427,  0.98094942])

#### Reshaping array:


In [102]:
# grab values from 0 through 19 in an array
arr = np.arange(20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [103]:
# reshape to be a 4 x 5 matrix
arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

#### Transpose:


In [104]:
# transpose
ex1 = np.array([[11,12],[21,22]])

ex1.T

array([[11, 21],
       [12, 22]])

#### Indexing using where():

In [105]:
x_1 = np.array([1,2,3,4,5])

y_1 = np.array([11,22,33,44,55])

filter = np.array([True, False, True, False, True])

In [106]:
out = np.where(filter, x_1, y_1)
print(out)

[ 1 22  3 44  5]


In [107]:
mat = np.random.rand(5,5)
mat

array([[0.28648775, 0.10584807, 0.50340496, 0.97767051, 0.74769136],
       [0.7362915 , 0.19641854, 0.27245822, 0.32866689, 0.97392829],
       [0.40532184, 0.65710088, 0.68353597, 0.41987328, 0.68405798],
       [0.85851254, 0.25683484, 0.89213962, 0.3029348 , 0.09837919],
       [0.43887743, 0.65496062, 0.75241614, 0.82194862, 0.9784971 ]])

In [108]:
np.where( mat > 0.5, 1000, -1)

array([[  -1,   -1, 1000, 1000, 1000],
       [1000,   -1,   -1,   -1, 1000],
       [  -1, 1000, 1000,   -1, 1000],
       [1000,   -1, 1000,   -1,   -1],
       [  -1, 1000, 1000, 1000, 1000]])

#### "any" or "all" conditionals:</p>

In [109]:
arr_bools = np.array([ True, False, True, True, False ])

In [110]:
arr_bools.any()

True

In [111]:
arr_bools.all()

False

#### Random Number Generation:


In [45]:
Y = np.random.normal(size = (1,5))[0]
print(Y)

[-0.18632425 -0.69059114  1.29699459  0.01286545 -0.49251192]


In [113]:
Z = np.random.randint(low=2,high=50,size=4)
print(Z)

[34 24 26 28]


In [114]:
np.random.permutation(Z) #return a new ordering of elements in Z

array([24, 34, 26, 28])

In [115]:
np.random.uniform(size=4) #uniform distribution

array([0.72846545, 0.15622442, 0.5961589 , 0.33264745])

In [116]:
np.random.normal(size=4) #normal distribution

array([ 0.25643389,  0.2668599 ,  0.2797328 , -1.48088849])

#### Merging data sets:

In [117]:
K = np.random.randint(low=2,high=50,size=(2,2))
print(K)

print()
M = np.random.randint(low=2,high=50,size=(2,2))
print(M)

[[ 4 18]
 [44 16]]

[[ 7 25]
 [22 29]]


In [118]:
np.vstack((K,M))

array([[ 4, 18],
       [44, 16],
       [ 7, 25],
       [22, 29]])

In [119]:
np.hstack((K,M))

array([[ 4, 18,  7, 25],
       [44, 16, 22, 29]])

In [120]:
np.concatenate([K, M], axis = 0)

array([[ 4, 18],
       [44, 16],
       [ 7, 25],
       [22, 29]])

In [121]:
np.concatenate([K, M.T], axis = 1)

array([[ 4, 18,  7, 22],
       [44, 16, 25, 29]])